### ISSUE TITLE
Change downsample parameter to adapt to sampling frequency

### ISSUE THREAD

**Issue by Hororohoruru** [ludovicdmt/t9_ssvep#2]
After reading #1 I was thinking that we could make a simple modification to the downsample parameter to adapt in case the sampling rate is different of what we used (500Hz), something like:

```
sfreq = 1000  # Or 500, or 250...
downsample = int(sfreq / 250)
```

I don't know if this could cause problems down the pipeline somewhere, but I think it should be OK

**Comment by ludovicdmt** [comment]
Thank you for your comment @Hororohoruru. 

I don't have a strong opinion on it because I have never tested with other devices, but I haven't done such automatic adaptation because it would induce interpolation if the base sampling rate is not a multiple of 250Hz. 

The interpolation could tamper the EEG signal. It may be better to avoid it and have instead a slightly higher reduced sampling rate. For instance if the base sampling rate of the EEG is 600Hz, it may produce better accuracy to downsample to 300Hz, instead of 250Hz. 

This should be investigated and tested so I didn't want to introduce anything automatic on this point.
